### ISSUE TITLE
Building for Node 9+

### ISSUE THREAD

**Issue by jochemstoel** [AtsushiSuzuki/node-clr#15]
Hi, I am not able to build clr for newer versions of Node. (any version since 8) Something about a nullpointer.
My build environent is configured properly. When I switch to older versions of Node it works fine but I need the latest ECMAScript features such as Promise.prototype.finally.

Can you please have a look at this stdout and see what is wrong? Thank you. 

```bash
C:\Users\Gebruiker\Desktop>npm i clr

> clr@0.0.18 install C:\Users\Gebruiker\Desktop\node_modules\clr
> node-gyp rebuild


C:\Users\Gebruiker\Desktop\node_modules\clr>if not defined npm_config_node_gyp (node "C:\bin\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\bin\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  DllMain.cc
  node-clr.cc
  Marshal.cc
  CLRObject.cc
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\DllMain.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\DllMain.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\DllMain.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\DllMain.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\Marshal.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\Marshal.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\node-clr.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\node-clr.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\Marshal.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\Marshal.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\node-clr.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\node-clr.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\CLRObject.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\CLRObject.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\CLRObject.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\CLRObject.cc)
..\src\node-clr.cc(185): warning C4996: 'v8::Value::BooleanValue': was declared deprecated [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(2568): note: see declaration of 'v8::Value::BooleanValue'
..\src\node-clr.cc(312): warning C4996: 'v8::Value::BooleanValue': was declared deprecated [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(2568): note: see declaration of 'v8::Value::BooleanValue'
..\src\node-clr.cc(351): warning C4996: 'v8::Value::BooleanValue': was declared deprecated [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  CLRBinder.cc
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(2568): note: see declaration of 'v8::Value::BooleanValue'
..\src\node-clr.cc(388): warning C4996: 'v8::Value::BooleanValue': was declared deprecated [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(2568): note: see declaration of 'v8::Value::BooleanValue'
..\src\CLRObject.cc(19): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(10254): note: see declaration of 'v8::Value::ToObject'
..\src\CLRObject.cc(78): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(10254): note: see declaration of 'v8::Value::ToObject'
..\src\CLRObject.cc(106): error C2039: 'Callee': is not a member of 'Nan::FunctionCallbackInfo<v8::Value>' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  c:\users\gebruiker\desktop\node_modules\nan\nan_callbacks.h(16): note: see declaration of 'Nan::FunctionCallbackInfo<v8::Value>'
..\src\CLRObject.cc(107): error C3536: 'ctor': cannot be used before it is initialized [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
..\src\CLRObject.cc(107): error C2664: 'v8::MaybeLocal<v8::Value> Nan::GetPrivate(v8::Local<v8::Object>,v8::Local<v8::String>)': cannot convert argument 1 from 'int' to 'v8::Local<v8::Object>' [C:
\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  ..\src\CLRObject.cc(107): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
..\src\CLRObject.cc(107): error C2228: left of '.ToLocalChecked' must have class/struct/union [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
..\src\CLRObject.cc(118): error C3536: 'typeName': cannot be used before it is initialized [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
..\src\CLRObject.cc(118): error C2665: 'CLRBinder::InvokeConstructor': none of the 2 overloads could convert all the argument types [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  c:\users\gebruiker\desktop\node_modules\clr\src\CLRBinder.h(45): note: could be 'System::Object ^CLRBinder::InvokeConstructor(System::Type ^,v8::Local<v8::Array>)' (compiling source file ..\src\
  CLRObject.cc)
  c:\users\gebruiker\desktop\node_modules\clr\src\CLRBinder.h(20): note: or       'System::Object ^CLRBinder::InvokeConstructor(v8::Local<v8::Value>,v8::Local<v8::Array>)' (compiling source file .
  .\src\CLRObject.cc)
  V8Function.cc
  ..\src\CLRObject.cc(118): note: while trying to match the argument list '(int, v8::Local<v8::Array>)'
..\src\CLRObject.cc(128): error C2664: 'v8::MaybeLocal<v8::Value> Nan::GetPrivate(v8::Local<v8::Object>,v8::Local<v8::String>)': cannot convert argument 1 from 'int' to 'v8::Local<v8::Object>' [C:
\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  ..\src\CLRObject.cc(128): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
..\src\CLRObject.cc(129): error C3536: 'initializer': cannot be used before it is initialized [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
..\src\CLRObject.cc(129): error C2039: 'IsEmpty': is not a member of 'System::Int32' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  V8Delegate.cc
..\src\CLRObject.cc(136): error C2039: 'ToLocalChecked': is not a member of 'System::Int32' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
..\src\CLRObject.cc(136): error C2672: 'v8::Local<v8::Function>::Cast': no matching overloaded function found [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
..\src\CLRObject.cc(136): error C2227: left of '->Call' must point to class/struct/union/generic type [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  V8InvocationException.cc
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\CLRBinder.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\CLRBinder.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\CLRBinder.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\CLRBinder.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\V8Function.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\V8Function.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\V8Delegate.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\V8Delegate.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\V8Function.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\V8Function.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\V8Delegate.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\V8Delegate.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\V8InvocationException.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4403): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\V8InvocationException.cc)
C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): error C2664: 'std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,st
d::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\V8InvocationException.cc)
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(4404): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\V8InvocationException.cc)
..\src\V8Function.cc(60): error C2512: 'v8::TryCatch': no appropriate default constructor available [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  C:\Users\Gebruiker\.node-gyp\11.10.0\include\node\v8.h(8814): note: see declaration of 'v8::TryCatch' (compiling source file ..\src\V8Function.cc)
..\src\V8Function.cc(61): warning C4996: 'Nan::MakeCallback': was declared deprecated [C:\Users\Gebruiker\Desktop\node_modules\clr\build\clr.vcxproj]
  C:\Users\Gebruiker\Desktop\node_modules\nan\nan.h(959): note: see declaration of 'Nan::MakeCallback'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\bin\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\bin\\nodejs\\node.exe" "C:\\bin\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Gebruiker\Desktop\node_modules\clr
gyp ERR! node -v v11.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Gebruiker\Desktop\package.json'
npm WARN Desktop No description
npm WARN Desktop No repository field.
npm WARN Desktop No README data
npm WARN Desktop No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clr@0.0.18 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the clr@0.0.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gebruiker\AppData\Roaming\npm-cache\_logs\2019-02-18T11_58_08_862Z-debug.log
```

**Comment by AtsushiSuzuki** [comment]
Although I'm glad to see you still using my software, I'm not able to have time to maintain this anymore, sorry.
I would recommend to migrate to something similar (Edge.js/C# scripting/something else).
Thank you.

**Comment by jochemstoel** [comment]
I know you said you don't have much time for this but I am willing to pay for getting this running on latest Node.

**Comment by AtsushiSuzuki** [comment]
Try latest master by `npm i "git://github.com/AtsushiSuzuki/node-clr.git#f6ff21b5938a794267597390d8d1fbb22a77fd02"`
I haven't succeeded to build that code without manually upgrading generated project manually, but this may work if you have proper build toolkit and windows sdk.

**Comment by jochemstoel** [comment]
It works!!! Thank you.
